### PR TITLE
Added Testomials and Review Page

### PR DESCRIPTION
**Pull request by tnawa103**
Added Testomials and Review Page

### CODE REVIEW

**Comment by tnawa103** [comment]
Please Allow me to push the Testimonial and review code pull

**Comment by ottawa-ehospital** [comment]
Your fork is not updated that is why your PR has a lot of conflicts please take a backup of your code and sync your fork and then add your code and send PR

**Comment by tnawa103** [comment]
Hi,

I made sure that my fork was updated before pushing the code.

Thanks,
Toufeeque



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tnawa103** [comment]
Hi,

Please check i have pushed again

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
